spring:
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: http://auth-server:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: auth-login
          uri: http://auth-server:8081
          predicates:
            - Path=/login
          filters:
            - SetPath=/login.html

        - id: auth-register
          uri: http://auth-server:8081
          predicates:
            - Path=/register
          filters:
            - SetPath=/register.html

        - id: qobuz-api
          uri: http://qobuz-api-gateway:8082
          predicates:
            - Path=/data/audio/**

        # LIBRARY SERVICE ROUTE
        - id: library-service
          uri: http://audio-library-service:8083
          predicates:
            - Path=/library/**

        # НОВЫЙ МАРШРУТ ДЛЯ КОРНЯ (Главная страница)
        - id: qobuz-root
          uri: http://qobuz-api-gateway:8082
          predicates:
            - Path=/
          filters:
            - SetPath=/index.html  # <--- Магия: меняем путь запроса на файл

        # ОСТАЛЬНАЯ СТАТИКА (JS, CSS)
        - id: qobuz-static
          uri: http://qobuz-api-gateway:8082
          predicates:
            - Path=/**