server:
  port: 8081
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: AUTH_SESSION
        path: /
        http-only: true
        same-site: lax
        secure: false

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://postgres:5432/soundspace_db
    username: soundowner
    password: secret_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET:very-long-and-secure-secret-key-that-must-be-at-least-256-bits}
  access-token-expiration: 60000    # 1 минута
  refresh-token-expiration: 90000   # 1.5 минуты

logging:
  level:
    org.springframework.security: DEBUG
