server:
  port: 8081

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:postgresql://localhost:5432/soundspace_db
    username: soundowner
    password: secret_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.security: DEBUG
