server:
  port: 8083

spring:
  application:
    name: audio-library-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/soundspace_library}
    username: ${SPRING_DATASOURCE_USERNAME:soundowner}
    password: ${SPRING_DATASOURCE_PASSWORD:secret_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:very-long-and-secure-secret-key-that-must-be-at-least-256-bits}

qobuz:
  gateway:
    url: ${QOBUZ_GATEWAY_URL:http://qobuz-api-gateway:8082}

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
